## Numpy

NumPy, short for Numerical Python, is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a large collection of mathematical functions to operate on these data structures. NumPy is particularly useful for numerical operations such as linear algebra, Fourier transform, and random number capabilities, and it provides an efficient way to handle large, multi-dimensional arrays and matrices, making it an essential part of various scientific and analytical tasks.

In [1]:
import numpy as np

## Numpy array

A NumPy array, often called an "ndarray", is a grid of values (all of the same type) that is indexed by a tuple of nonnegative integers. They are more efficient and provide more functionality compared to Python's built-in list data structure.

In [2]:
# define a ndarray
# ndarray
z = np.zeros(10)
print(z)
print('data type:', type(z))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
data type: <class 'numpy.ndarray'>


In [3]:
# Create a ndarray with all 1 
all_one = np.ones(5)
print(all_one)

[1. 1. 1. 1. 1.]


In [4]:
# create a ndarray having number from 0 to 9
z = np.arange(10)
print(z)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# from 2 to 10, with 5 elements
z = np.linspace(2, 10, 5) 
print(z)

[ 2.  4.  6.  8. 10.]


In [6]:
print(np.linspace(1,10,3))

[ 1.   5.5 10. ]


In [7]:
# a ndarray with random interger
np.random.seed(9)
z_random = np.random.randint(10, size = 6)
print(z_random)

[5 6 8 6 1 6]


In [8]:
# 2D ndarray
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# matrix transpose
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
# matrix multiplication
b = np.array([[2,5,8],[4,7,5],[1,3,2]])
print(a.dot(b))

[[ 13  28  24]
 [ 34  73  69]
 [ 55 118 114]]


In [11]:
# many useful buildin function in numpy
print(np.sum(a))
print(np.prod(a))
print(np.mean(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.argmin(a))
print(np.argmax(a))

45
362880
5.0
2.581988897471611
6.666666666666667
1
9
0
8


In [12]:
# set threshold
print(np.where(a > 5, 100, 0))

[[  0   0   0]
 [  0   0 100]
 [100 100 100]]


## Pandas

Offering data structures and operations for manipulating numerical tables and time series.



In [13]:
#import necessary libs
import numpy as np
import pandas as pd

#### 01. Data Structure
1) Pandas Series: contain single list with index

In [14]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

2) Pandas Dataframe: collection of Pandas series

In [15]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [16]:
mat = np.random.randn(6, 4)
mat

array([[-0.29547281, -1.02560458, -1.99682969, -0.05791935],
       [ 1.39815718, -0.75103355,  0.07269019,  0.61763898],
       [ 0.15805181,  0.54083288,  1.96869579,  0.91502712],
       [-0.62301069,  1.3230902 , -1.47225847, -0.04570996],
       [ 0.85806095,  1.7804395 , -0.74550456,  0.14062501],
       [-0.22819673, -1.19135916, -1.05313233,  0.27441526]])

In [17]:
df = pd.DataFrame(mat, index=dates, columns=list("ABCD"))
df

A         B         C         D
2013-01-01 -0.295473 -1.025605 -1.996830 -0.057919
2013-01-02  1.398157 -0.751034  0.072690  0.617639
2013-01-03  0.158052  0.540833  1.968696  0.915027
2013-01-04 -0.623011  1.323090 -1.472258 -0.045710
2013-01-05  0.858061  1.780439 -0.745505  0.140625
2013-01-06 -0.228197 -1.191359 -1.053132  0.274415

In [18]:
df2 = pd.DataFrame(
        {
            "A": np.arange(4),
            "B": pd.Timestamp("20130102"),
            "C": pd.Series(1, index=list(range(4)), dtype="float32"),
            "D": np.array([3] * 4, dtype="int32"),
            "E": pd.Categorical(["test", "train", "test", "train"]),
            "F": "foo",
        }
    )
df2

A          B    C  D      E    F
0  0 2013-01-02  1.0  3   test  foo
1  1 2013-01-02  1.0  3  train  foo
2  2 2013-01-02  1.0  3   test  foo
3  3 2013-01-02  1.0  3  train  foo

In [19]:
df2.dtypes

A            int64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

### 01. Viewing Data

In [20]:
df.head(2)

A         B        C         D
2013-01-01 -0.295473 -1.025605 -1.99683 -0.057919
2013-01-02  1.398157 -0.751034  0.07269  0.617639

In [21]:
df.tail(2)

A         B         C         D
2013-01-05  0.858061  1.780439 -0.745505  0.140625
2013-01-06 -0.228197 -1.191359 -1.053132  0.274415

In [22]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [23]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [24]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.211265  0.112728 -0.537723  0.307346
std    0.771468  1.278440  1.411801  0.387945
min   -0.623011 -1.191359 -1.996830 -0.057919
25%   -0.278654 -0.956962 -1.367477  0.000874
50%   -0.035072 -0.105100 -0.899318  0.207520
75%    0.683059  1.127526 -0.131858  0.531833
max    1.398157  1.780439  1.968696  0.915027

### 03. Info Selection

#### 1) select column

In [25]:
df

A         B         C         D
2013-01-01 -0.295473 -1.025605 -1.996830 -0.057919
2013-01-02  1.398157 -0.751034  0.072690  0.617639
2013-01-03  0.158052  0.540833  1.968696  0.915027
2013-01-04 -0.623011  1.323090 -1.472258 -0.045710
2013-01-05  0.858061  1.780439 -0.745505  0.140625
2013-01-06 -0.228197 -1.191359 -1.053132  0.274415

In [26]:
df.A

2013-01-01   -0.295473
2013-01-02    1.398157
2013-01-03    0.158052
2013-01-04   -0.623011
2013-01-05    0.858061
2013-01-06   -0.228197
Freq: D, Name: A, dtype: float64

In [27]:
df['A']

2013-01-01   -0.295473
2013-01-02    1.398157
2013-01-03    0.158052
2013-01-04   -0.623011
2013-01-05    0.858061
2013-01-06   -0.228197
Freq: D, Name: A, dtype: float64

In [28]:
df[['A','B']]

A         B
2013-01-01 -0.295473 -1.025605
2013-01-02  1.398157 -0.751034
2013-01-03  0.158052  0.540833
2013-01-04 -0.623011  1.323090
2013-01-05  0.858061  1.780439
2013-01-06 -0.228197 -1.191359

#### 2）select by index

In [29]:
df[1:4]

A         B         C         D
2013-01-02  1.398157 -0.751034  0.072690  0.617639
2013-01-03  0.158052  0.540833  1.968696  0.915027
2013-01-04 -0.623011  1.323090 -1.472258 -0.045710

#### 3) select by label: pd.loc

In [30]:
df.loc['2013-01-03']

A    0.158052
B    0.540833
C    1.968696
D    0.915027
Name: 2013-01-03 00:00:00, dtype: float64

In [31]:
df.loc[:,['A','B']]

A         B
2013-01-01 -0.295473 -1.025605
2013-01-02  1.398157 -0.751034
2013-01-03  0.158052  0.540833
2013-01-04 -0.623011  1.323090
2013-01-05  0.858061  1.780439
2013-01-06 -0.228197 -1.191359

In [32]:
df.loc["20130102", ["A"]]

A    1.398157
Name: 2013-01-02 00:00:00, dtype: float64

#### 4) select by position: pd.iloc

In [33]:
df.iloc[3]

A   -0.623011
B    1.323090
C   -1.472258
D   -0.045710
Name: 2013-01-04 00:00:00, dtype: float64

In [34]:
df.iloc[3:5, 0:2]

A         B
2013-01-04 -0.623011  1.323090
2013-01-05  0.858061  1.780439

In [35]:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2013-01-02  1.398157  0.072690
2013-01-03  0.158052  1.968696
2013-01-05  0.858061 -0.745505

In [36]:
df.iloc[1:3, :]

A         B         C         D
2013-01-02  1.398157 -0.751034  0.072690  0.617639
2013-01-03  0.158052  0.540833  1.968696  0.915027

### 04. Filter Data with Conditional Statement

In [37]:
df

A         B         C         D
2013-01-01 -0.295473 -1.025605 -1.996830 -0.057919
2013-01-02  1.398157 -0.751034  0.072690  0.617639
2013-01-03  0.158052  0.540833  1.968696  0.915027
2013-01-04 -0.623011  1.323090 -1.472258 -0.045710
2013-01-05  0.858061  1.780439 -0.745505  0.140625
2013-01-06 -0.228197 -1.191359 -1.053132  0.274415

In [38]:
df[df["A"] > 0]

A         B         C         D
2013-01-02  1.398157 -0.751034  0.072690  0.617639
2013-01-03  0.158052  0.540833  1.968696  0.915027
2013-01-05  0.858061  1.780439 -0.745505  0.140625

In [39]:
df["E"] = ["one", "one", "two", "three", "four", "three"]
df

A         B         C         D      E
2013-01-01 -0.295473 -1.025605 -1.996830 -0.057919    one
2013-01-02  1.398157 -0.751034  0.072690  0.617639    one
2013-01-03  0.158052  0.540833  1.968696  0.915027    two
2013-01-04 -0.623011  1.323090 -1.472258 -0.045710  three
2013-01-05  0.858061  1.780439 -0.745505  0.140625   four
2013-01-06 -0.228197 -1.191359 -1.053132  0.274415  three

In [40]:
df[df["E"].isin(["two", "four"])]

A         B         C         D     E
2013-01-03  0.158052  0.540833  1.968696  0.915027   two
2013-01-05  0.858061  1.780439 -0.745505  0.140625  four

### 04. Data Operation
1) Stats operation:
mean, median, sum ...

In [47]:
df = df.drop(columns="E")
df.mean()

A    0.211265
B    0.112728
C   -0.537723
D    0.307346
dtype: float64

In [48]:
df.mean(axis = 1)

2013-01-01   -0.843957
2013-01-02    0.334363
2013-01-03    0.895652
2013-01-04   -0.204472
2013-01-05    0.508405
2013-01-06   -0.549568
Freq: D, dtype: float64

2) Apply

In [49]:
df.drop(columns = ['E'], inplace = True)
df

KeyError: "['E'] not found in axis"

In [50]:
df.apply(np.sqrt)

A         B         C         D
2013-01-01       NaN       NaN       NaN       NaN
2013-01-02  1.182437       NaN  0.269611  0.785900
2013-01-03  0.397557  0.735413  1.403102  0.956571
2013-01-04       NaN  1.150257       NaN       NaN
2013-01-05  0.926316  1.334331       NaN  0.375000
2013-01-06       NaN       NaN       NaN  0.523847

In [51]:
df.apply(np.sum)

A    1.267590
B    0.676365
C   -3.226339
D    1.844077
dtype: float64

In [52]:
df.sum()

A    1.267590
B    0.676365
C   -3.226339
D    1.844077
dtype: float64

In [53]:
df['A'].apply(lambda x: 0.5*x+0.5)

2013-01-01    0.352264
2013-01-02    1.199079
2013-01-03    0.579026
2013-01-04    0.188495
2013-01-05    0.929030
2013-01-06    0.385902
Freq: D, Name: A, dtype: float64

### 05. SQL Style Operation
#### 1) Join 
SQL Clause: 
select * from df2
left join df3
on df2.A = df3.A

In [54]:
df3 = pd.DataFrame(
        {
            "A": np.arange(4),
            "G": ['right','left','right','left'],
            "H": [100,200,300,400]
        }
    )
df3

A      G    H
0  0  right  100
1  1   left  200
2  2  right  300
3  3   left  400

In [55]:
df2

A          B    C  D      E    F
0  0 2013-01-02  1.0  3   test  foo
1  1 2013-01-02  1.0  3  train  foo
2  2 2013-01-02  1.0  3   test  foo
3  3 2013-01-02  1.0  3  train  foo

In [56]:
joint = df2.merge(df3, on = 'A', how = 'left')
joint

A          B    C  D      E    F      G    H
0  0 2013-01-02  1.0  3   test  foo  right  100
1  1 2013-01-02  1.0  3  train  foo   left  200
2  2 2013-01-02  1.0  3   test  foo  right  300
3  3 2013-01-02  1.0  3  train  foo   left  400

#### 2) Grouping  
SQL: select sum(H) from joint  
group by E

In [57]:
joint.groupby('E')['H'].mean()

/var/folders/vl/9w9rx2q5545bh7r3xxpffqh40000gn/T/ipykernel_31303/4024439776.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  joint.groupby('E')['H'].mean()


E
test     200.0
train    300.0
Name: H, dtype: float64